baseURL = "https://lichengping.com/"
languageCode = "en"
title = "LI Chengping"

[params]
  description = "LI Chengping's personal homepage"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true
  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)'], ['$', '$']]
